### ISSUE TITLE
Log file overwrite

### ISSUE THREAD

**Issue by wsnoble** [freejstone/CONGA#12]
Mike Riffle said: "I think it'd be nice if the log file only had the output of the most recent run of CONGA. It looks like each run concatenates to the same log, which makes it harder to read. And, importantly, it complicates programmatically processing the log file to get details for the most recent run."

I agree with this.  I'd recommend having the log file named something like <root>.log.txt, where <root> is specified by the user, and then having the program refuse to run if that file already exists. You can provide an --overwrite option if you want to be able to clobber the log file.

**Comment by freejstone** [comment]
--overwrite option has been added with the recommended functionality. Thanks Mike and Bill.
