### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by wsnoble** [freejstone/CONGA#13]
In addition to handling Python versioning, I think it'd be import to nail down versioning of CONGA, itself.  This can be handled by GitHub actions that can run code/programs triggered by making a new release using the GitHub interface. What I normally do with GitHub actions are: 1) add the program files, themselves, as assets to the release on GitHub, 2) create a Docker image and push to Docker Hub, tagged using semantic versioning. It'd also be good if CONGA output its version number when it runs (sorry if it already does and I didn't see it).
GitHub can also automate the creation of versioned pip and conda packages,

**Comment by freejstone** [comment]
Now using versioneer to automatically bump version numbers according to git tags and using github actions to create new releases when git tags are pushed. Need to also automate a changelog which I will add an issue for.
