### ISSUE TITLE
Automate testing via github actions

### ISSUE THREAD

**Issue by wsnoble** [freejstone/CONGA#14]
From Mike Riffle: "GitHub actions can run some tests to ensure things work whenever you push to the repo/accept a pull request. E.g., it can run CONGA on some sample files to ensure it runs to completion."

In practice, the tests that run on a push should run very quickly, so running on full sample files may not be feasible. But you should ideally implement unit tests using the pytest package and then have those get run via github actions.  Check out the Casanovo repo for details on how to do this, or ask Wout and Will.

**Comment by mriffle** [comment]
For what it's worth, processing the sample data is actually pretty fast.

**Comment by freejstone** [comment]
Testing both sample data and unit tests with pytest using github actions since it seems fast enough.
