### ISSUE TITLE
Headline line contains underscores instead of tabs

### ISSUE THREAD

**Issue by mriffle** [freejstone/CONGA#17]
My run of CONGA is producing this header line in the targets results file:

```
score   delta_mass      peptide rank    search_file     scan_charge_sp_neutral_mass
```

I think it is supposed to be:

```
score   delta_mass      peptide rank    search_file     scan	charge	sp	neutral_mass
```

BTW, what is `sp`?

**Comment by freejstone** [comment]
Thanks Mike! Yes not sure why I adopted a different convention for Comet search files. I'll fix this when I get back to my computer hopefully later today. 

(sp was my short hand for spectrum... probably not the best considering there is the sp score)

Cheers,

Jack

**Comment by mriffle** [comment]
Ah, guess it should actually be this then?

```
score   delta_mass      peptide rank    search_file     scan	charge	sp_neutral_mass
```

Going to assume that for now, working on the Limelight XML converter

**Comment by freejstone** [comment]
Yep that's right, though I think I will go with spectrum_neutral_mass now that it is split up and not too long.

**Comment by freejstone** [comment]
Okay I was able to attend this earlier than I thought -- should work as desired now.

**Comment by mriffle** [comment]
Ah, upon closer inspection of the data in the rows, it looks like it should actually be:

```
score   delta_mass      peptide rank    search_file	charge	spectrum_neutral_mass	scan
```

**Comment by freejstone** [comment]
Ah wow, how silly. Okay yes now It _should_ be okay.

**Comment by mriffle** [comment]
All looks good now, thanks
